/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import { BaseResource, CloudError, AzureServiceClientOptions } from "@azure/ms-rest-azure-js";
import * as msRest from "@azure/ms-rest-js";

export { BaseResource, CloudError };

/**
 * Definition of the job stream.
 */
export interface JobStream {
  /**
   * Gets or sets the id of the resource.
   */
  id?: string;
  /**
   * Gets or sets the id of the job stream.
   */
  jobStreamId?: string;
  /**
   * Gets or sets the creation time of the job.
   */
  time?: Date;
  /**
   * Gets or sets the stream type. Possible values include: 'Progress', 'Output', 'Warning',
   * 'Error', 'Debug', 'Verbose', 'Any'
   */
  streamType?: JobStreamType;
  /**
   * Gets or sets the stream text.
   */
  streamText?: string;
  /**
   * Gets or sets the summary.
   */
  summary?: string;
  /**
   * Gets or sets the values of the job stream.
   */
  value?: { [propertyName: string]: any };
}

/**
 * Definition of the runbook property type.
 */
export interface ContentHash {
  /**
   * Gets or sets the content hash algorithm used to hash the content.
   */
  algorithm: string;
  /**
   * Gets or sets expected hash value of the content.
   */
  value: string;
}

/**
 * Definition of the content link.
 */
export interface ContentLink {
  /**
   * Gets or sets the uri of the runbook content.
   */
  uri?: string;
  /**
   * Gets or sets the hash.
   */
  contentHash?: ContentHash;
  /**
   * Gets or sets the version of the content.
   */
  version?: string;
}

/**
 * Definition of the runbook parameter type.
 */
export interface RunbookParameter {
  /**
   * Gets or sets the type of the parameter.
   */
  type?: string;
  /**
   * Gets or sets a Boolean value to indicate whether the parameter is mandatory or not.
   */
  isMandatory?: boolean;
  /**
   * Get or sets the position of the parameter.
   */
  position?: number;
  /**
   * Gets or sets the default value of parameter.
   */
  defaultValue?: string;
}

/**
 * An interface representing RunbookDraft.
 */
export interface RunbookDraft {
  /**
   * Gets or sets whether runbook is in edit mode.
   */
  inEdit?: boolean;
  /**
   * Gets or sets the draft runbook content link.
   */
  draftContentLink?: ContentLink;
  /**
   * Gets or sets the creation time of the runbook draft.
   */
  creationTime?: Date;
  /**
   * Gets or sets the last modified time of the runbook draft.
   */
  lastModifiedTime?: Date;
  /**
   * Gets or sets the runbook draft parameters.
   */
  parameters?: { [propertyName: string]: RunbookParameter };
  /**
   * Gets or sets the runbook output types.
   */
  outputTypes?: string[];
}

/**
 * The core properties of ARM resources
 */
export interface Resource extends BaseResource {
  /**
   * Fully qualified resource Id for the resource
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly id?: string;
  /**
   * The name of the resource
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly name?: string;
  /**
   * The type of the resource.
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly type?: string;
}

/**
 * The resource model definition for a ARM tracked top level resource
 */
export interface TrackedResource extends Resource {
  /**
   * Resource tags.
   */
  tags?: { [propertyName: string]: string };
  /**
   * The Azure Region where the resource lives
   */
  location?: string;
}

/**
 * Definition of the runbook type.
 */
export interface Runbook extends TrackedResource {
  /**
   * Gets or sets the type of the runbook. Possible values include: 'Script', 'Graph',
   * 'PowerShellWorkflow', 'PowerShell', 'GraphPowerShellWorkflow', 'GraphPowerShell'
   */
  runbookType?: RunbookTypeEnum;
  /**
   * Gets or sets the published runbook content link.
   */
  publishContentLink?: ContentLink;
  /**
   * Gets or sets the state of the runbook. Possible values include: 'New', 'Edit', 'Published'
   */
  state?: RunbookState;
  /**
   * Gets or sets verbose log option.
   */
  logVerbose?: boolean;
  /**
   * Gets or sets progress log option.
   */
  logProgress?: boolean;
  /**
   * Gets or sets the option to log activity trace of the runbook.
   */
  logActivityTrace?: number;
  /**
   * Gets or sets the job count of the runbook.
   */
  jobCount?: number;
  /**
   * Gets or sets the runbook parameters.
   */
  parameters?: { [propertyName: string]: RunbookParameter };
  /**
   * Gets or sets the runbook output types.
   */
  outputTypes?: string[];
  /**
   * Gets or sets the draft runbook properties.
   */
  draft?: RunbookDraft;
  /**
   * Gets or sets the provisioning state of the runbook. Possible values include: 'Succeeded'
   */
  provisioningState?: RunbookProvisioningState;
  /**
   * Gets or sets the last modified by.
   */
  lastModifiedBy?: string;
  /**
   * Gets or sets the creation time.
   */
  creationTime?: Date;
  /**
   * Gets or sets the last modified time.
   */
  lastModifiedTime?: Date;
  /**
   * Gets or sets the description.
   */
  description?: string;
  /**
   * Gets or sets the etag of the resource.
   */
  etag?: string;
}

/**
 * The parameters supplied to the create or update runbook operation.
 */
export interface RunbookCreateOrUpdateParameters {
  /**
   * Gets or sets verbose log option.
   */
  logVerbose?: boolean;
  /**
   * Gets or sets progress log option.
   */
  logProgress?: boolean;
  /**
   * Gets or sets the type of the runbook. Possible values include: 'Script', 'Graph',
   * 'PowerShellWorkflow', 'PowerShell', 'GraphPowerShellWorkflow', 'GraphPowerShell'
   */
  runbookType: RunbookTypeEnum;
  /**
   * Gets or sets the draft runbook properties.
   */
  draft?: RunbookDraft;
  /**
   * Gets or sets the published runbook content link.
   */
  publishContentLink?: ContentLink;
  /**
   * Gets or sets the description of the runbook.
   */
  description?: string;
  /**
   * Gets or sets the activity-level tracing options of the runbook.
   */
  logActivityTrace?: number;
  /**
   * Gets or sets the name of the resource.
   */
  name?: string;
  /**
   * Gets or sets the location of the resource.
   */
  location?: string;
  /**
   * Gets or sets the tags attached to the resource.
   */
  tags?: { [propertyName: string]: string };
}

/**
 * The parameters supplied to the update runbook operation.
 */
export interface RunbookUpdateParameters {
  /**
   * Gets or sets the description of the runbook.
   */
  description?: string;
  /**
   * Gets or sets verbose log option.
   */
  logVerbose?: boolean;
  /**
   * Gets or sets progress log option.
   */
  logProgress?: boolean;
  /**
   * Gets or sets the activity-level tracing options of the runbook.
   */
  logActivityTrace?: number;
  /**
   * Gets or sets the name of the resource.
   */
  name?: string;
  /**
   * Gets or sets the location of the resource.
   */
  location?: string;
  /**
   * Gets or sets the tags attached to the resource.
   */
  tags?: { [propertyName: string]: string };
}

/**
 * The response model for the undo edit runbook operation.
 */
export interface RunbookDraftUndoEditResult {
  /**
   * Possible values include: 'Continue', 'SwitchingProtocols', 'OK', 'Created', 'Accepted',
   * 'NonAuthoritativeInformation', 'NoContent', 'ResetContent', 'PartialContent',
   * 'MultipleChoices', 'Ambiguous', 'MovedPermanently', 'Moved', 'Found', 'Redirect', 'SeeOther',
   * 'RedirectMethod', 'NotModified', 'UseProxy', 'Unused', 'TemporaryRedirect',
   * 'RedirectKeepVerb', 'BadRequest', 'Unauthorized', 'PaymentRequired', 'Forbidden', 'NotFound',
   * 'MethodNotAllowed', 'NotAcceptable', 'ProxyAuthenticationRequired', 'RequestTimeout',
   * 'Conflict', 'Gone', 'LengthRequired', 'PreconditionFailed', 'RequestEntityTooLarge',
   * 'RequestUriTooLong', 'UnsupportedMediaType', 'RequestedRangeNotSatisfiable',
   * 'ExpectationFailed', 'UpgradeRequired', 'InternalServerError', 'NotImplemented', 'BadGateway',
   * 'ServiceUnavailable', 'GatewayTimeout', 'HttpVersionNotSupported'
   */
  statusCode?: HttpStatusCode;
  requestId?: string;
}

/**
 * The parameters supplied to the create test job operation.
 */
export interface TestJobCreateParameters {
  /**
   * Gets or sets the parameters of the test job.
   */
  parameters?: { [propertyName: string]: string };
  /**
   * Gets or sets the runOn which specifies the group name where the job is to be executed.
   */
  runOn?: string;
}

/**
 * Definition of the test job.
 */
export interface TestJob {
  /**
   * Gets or sets the creation time of the test job.
   */
  creationTime?: Date;
  /**
   * Gets or sets the status of the test job.
   */
  status?: string;
  /**
   * Gets or sets the status details of the test job.
   */
  statusDetails?: string;
  /**
   * Gets or sets the runOn which specifies the group name where the job is to be executed.
   */
  runOn?: string;
  /**
   * Gets or sets the start time of the test job.
   */
  startTime?: Date;
  /**
   * Gets or sets the end time of the test job.
   */
  endTime?: Date;
  /**
   * Gets or sets the exception of the test job.
   */
  exception?: string;
  /**
   * Gets or sets the last modified time of the test job.
   */
  lastModifiedTime?: Date;
  /**
   * Gets or sets the last status modified time of the test job.
   */
  lastStatusModifiedTime?: Date;
  /**
   * Gets or sets the parameters of the test job.
   */
  parameters?: { [propertyName: string]: string };
  /**
   * The activity-level tracing options of the runbook.
   */
  logActivityTrace?: number;
}

/**
 * The parameters supplied to the create or update draft runbook properties.
 */
export interface RunbookCreateOrUpdateDraftProperties {
  /**
   * Gets or sets verbose log option.
   */
  logVerbose?: boolean;
  /**
   * Gets or sets progress log option.
   */
  logProgress?: boolean;
  /**
   * Gets or sets the type of the runbook. Possible values include: 'Script', 'Graph',
   * 'PowerShellWorkflow', 'PowerShell', 'GraphPowerShellWorkflow', 'GraphPowerShell'
   */
  runbookType: RunbookTypeEnum;
  /**
   * Gets or sets the draft runbook properties.
   */
  draft: RunbookDraft;
  /**
   * Gets or sets the description of the runbook.
   */
  description?: string;
  /**
   * Gets or sets the activity-level tracing options of the runbook.
   */
  logActivityTrace?: number;
}

/**
 * The parameters supplied to the create or update runbook operation.
 */
export interface RunbookCreateOrUpdateDraftParameters {
  /**
   * Content of the Runbook.
   */
  runbookContent: string;
}

/**
 * ARM proxy resource.
 */
export interface ProxyResource extends Resource {
}

/**
 * Error response of an operation failure
 */
export interface ErrorResponse {
  /**
   * Error code
   */
  code?: string;
  /**
   * Error message indicating why the operation failed.
   */
  message?: string;
}

/**
 * The account SKU.
 */
export interface Sku {
  /**
   * Gets or sets the SKU name of the account. Possible values include: 'Free', 'Basic'
   */
  name: SkuNameEnum;
  /**
   * Gets or sets the SKU family.
   */
  family?: string;
  /**
   * Gets or sets the SKU capacity.
   */
  capacity?: number;
}

/**
 * Definition of the automation account type.
 */
export interface AutomationAccount extends TrackedResource {
  /**
   * Gets or sets the SKU of account.
   */
  sku?: Sku;
  /**
   * Gets or sets the last modified by.
   */
  lastModifiedBy?: string;
  /**
   * Gets status of account. Possible values include: 'Ok', 'Unavailable', 'Suspended'
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly state?: AutomationAccountState;
  /**
   * Gets the creation time.
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly creationTime?: Date;
  /**
   * Gets the last modified time.
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly lastModifiedTime?: Date;
  /**
   * Gets or sets the description.
   */
  description?: string;
  /**
   * Gets or sets the etag of the resource.
   */
  etag?: string;
}

/**
 * The parameters supplied to the create or update automation account operation.
 */
export interface AutomationAccountCreateOrUpdateParameters {
  /**
   * Gets or sets account SKU.
   */
  sku?: Sku;
  /**
   * Gets or sets name of the resource.
   */
  name?: string;
  /**
   * Gets or sets the location of the resource.
   */
  location?: string;
  /**
   * Gets or sets the tags attached to the resource.
   */
  tags?: { [propertyName: string]: string };
}

/**
 * Provider, Resource and Operation values
 */
export interface OperationDisplay {
  /**
   * Service provider: Microsoft.Automation
   */
  provider?: string;
  /**
   * Resource on which the operation is performed: Runbooks, Jobs etc.
   */
  resource?: string;
  /**
   * Operation type: Read, write, delete, etc.
   */
  operation?: string;
}

/**
 * Automation REST API operation
 */
export interface Operation {
  /**
   * Operation name: {provider}/{resource}/{operation}
   */
  name?: string;
  /**
   * Provider, Resource and Operation values
   */
  display?: OperationDisplay;
}

/**
 * Definition of the statistic.
 */
export interface Statistics {
  /**
   * Gets the property value of the statistic.
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly counterProperty?: string;
  /**
   * Gets the value of the statistic.
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly counterValue?: number;
  /**
   * Gets the startTime of the statistic.
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly startTime?: Date;
  /**
   * Gets the endTime of the statistic.
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly endTime?: Date;
  /**
   * Gets the id.
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly id?: string;
}

/**
 * Definition of usage counter name.
 */
export interface UsageCounterName {
  /**
   * Gets or sets the usage counter name.
   */
  value?: string;
  /**
   * Gets or sets the localized usage counter name.
   */
  localizedValue?: string;
}

/**
 * Definition of Usage.
 */
export interface Usage {
  /**
   * Gets or sets the id of the resource.
   */
  id?: string;
  /**
   * Gets or sets the usage counter name.
   */
  name?: UsageCounterName;
  /**
   * Gets or sets the usage unit name.
   */
  unit?: string;
  /**
   * Gets or sets the current usage value.
   */
  currentValue?: number;
  /**
   * Gets or sets max limit. -1 for unlimited
   */
  limit?: number;
  /**
   * Gets or sets the throttle status.
   */
  throttleStatus?: string;
}

/**
 * Automation key which is used to register a DSC Node
 */
export interface Key {
  /**
   * Automation key name. Possible values include: 'Primary', 'Secondary'
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly keyName?: AutomationKeyName;
  /**
   * Automation key permissions. Possible values include: 'Read', 'Full'
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly permissions?: AutomationKeyPermissions;
  /**
   * Value of the Automation Key used for registration.
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly value?: string;
}

/**
 * An interface representing KeyListResult.
 */
export interface KeyListResult {
  /**
   * Lists the automation keys.
   */
  keys?: Key[];
}

/**
 * The parameters supplied to the update automation account operation.
 */
export interface AutomationAccountUpdateParameters {
  /**
   * Gets or sets account SKU.
   */
  sku?: Sku;
  /**
   * Gets or sets the name of the resource.
   */
  name?: string;
  /**
   * Gets or sets the location of the resource.
   */
  location?: string;
  /**
   * Gets or sets the tags attached to the resource.
   */
  tags?: { [propertyName: string]: string };
}

/**
 * The runbook property associated with the entity.
 */
export interface RunbookAssociationProperty {
  /**
   * Gets or sets the name of the runbook.
   */
  name?: string;
}

/**
 * Definition of the job.
 */
export interface Job extends ProxyResource {
  /**
   * Gets or sets the runbook.
   */
  runbook?: RunbookAssociationProperty;
  /**
   * Gets or sets the job started by.
   */
  startedBy?: string;
  /**
   * Gets or sets the runOn which specifies the group name where the job is to be executed.
   */
  runOn?: string;
  /**
   * Gets or sets the id of the job.
   */
  jobId?: string;
  /**
   * Gets or sets the creation time of the job.
   */
  creationTime?: Date;
  /**
   * Gets or sets the status of the job. Possible values include: 'New', 'Activating', 'Running',
   * 'Completed', 'Failed', 'Stopped', 'Blocked', 'Suspended', 'Disconnected', 'Suspending',
   * 'Stopping', 'Resuming', 'Removing'
   */
  status?: JobStatus;
  /**
   * Gets or sets the status details of the job.
   */
  statusDetails?: string;
  /**
   * Gets or sets the start time of the job.
   */
  startTime?: Date;
  /**
   * Gets or sets the end time of the job.
   */
  endTime?: Date;
  /**
   * Gets or sets the exception of the job.
   */
  exception?: string;
  /**
   * Gets or sets the last modified time of the job.
   */
  lastModifiedTime?: Date;
  /**
   * Gets or sets the last status modified time of the job.
   */
  lastStatusModifiedTime?: Date;
  /**
   * Gets or sets the parameters of the job.
   */
  parameters?: { [propertyName: string]: string };
  /**
   * The current provisioning state of the job. Possible values include: 'Failed', 'Succeeded',
   * 'Suspended', 'Processing'
   */
  provisioningState?: JobProvisioningState;
}

/**
 * Job collection item properties.
 */
export interface JobCollectionItem extends ProxyResource {
  /**
   * The runbook association.
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly runbook?: RunbookAssociationProperty;
  /**
   * The id of the job.
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly jobId?: string;
  /**
   * The creation time of the job.
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly creationTime?: Date;
  /**
   * The status of the job. Possible values include: 'New', 'Activating', 'Running', 'Completed',
   * 'Failed', 'Stopped', 'Blocked', 'Suspended', 'Disconnected', 'Suspending', 'Stopping',
   * 'Resuming', 'Removing'
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly status?: JobStatus;
  /**
   * The start time of the job.
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly startTime?: Date;
  /**
   * The end time of the job.
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly endTime?: Date;
  /**
   * The last modified time of the job.
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly lastModifiedTime?: Date;
  /**
   * The provisioning state of a resource.
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly provisioningState?: string;
  /**
   * Specifies the runOn group name where the job was executed.
   */
  runOn?: string;
}

/**
 * The parameters supplied to the create job operation.
 */
export interface JobCreateParameters {
  /**
   * Gets or sets the runbook.
   */
  runbook?: RunbookAssociationProperty;
  /**
   * Gets or sets the parameters of the job.
   */
  parameters?: { [propertyName: string]: string };
  /**
   * Gets or sets the runOn which specifies the group name where the job is to be executed.
   */
  runOn?: string;
}

/**
 * Optional Parameters.
 */
export interface TestJobStreamsListByTestJobOptionalParams extends msRest.RequestOptionsBase {
  /**
   * The filter to apply on the operation.
   */
  filter?: string;
}

/**
 * Optional Parameters.
 */
export interface TestJobStreamsListByTestJobNextOptionalParams extends msRest.RequestOptionsBase {
  /**
   * The filter to apply on the operation.
   */
  filter?: string;
}

/**
 * Optional Parameters.
 */
export interface StatisticsListByAutomationAccountOptionalParams extends msRest.RequestOptionsBase {
  /**
   * The filter to apply on the operation.
   */
  filter?: string;
}

/**
 * Optional Parameters.
 */
export interface JobGetOutputOptionalParams extends msRest.RequestOptionsBase {
  /**
   * Identifies this specific client request.
   */
  clientRequestId?: string;
}

/**
 * Optional Parameters.
 */
export interface JobGetRunbookContentOptionalParams extends msRest.RequestOptionsBase {
  /**
   * Identifies this specific client request.
   */
  clientRequestId?: string;
}

/**
 * Optional Parameters.
 */
export interface JobSuspendOptionalParams extends msRest.RequestOptionsBase {
  /**
   * Identifies this specific client request.
   */
  clientRequestId?: string;
}

/**
 * Optional Parameters.
 */
export interface JobStopOptionalParams extends msRest.RequestOptionsBase {
  /**
   * Identifies this specific client request.
   */
  clientRequestId?: string;
}

/**
 * Optional Parameters.
 */
export interface JobGetOptionalParams extends msRest.RequestOptionsBase {
  /**
   * Identifies this specific client request.
   */
  clientRequestId?: string;
}

/**
 * Optional Parameters.
 */
export interface JobCreateOptionalParams extends msRest.RequestOptionsBase {
  /**
   * Identifies this specific client request.
   */
  clientRequestId?: string;
}

/**
 * Optional Parameters.
 */
export interface JobListByAutomationAccountOptionalParams extends msRest.RequestOptionsBase {
  /**
   * The filter to apply on the operation.
   */
  filter?: string;
  /**
   * Identifies this specific client request.
   */
  clientRequestId?: string;
}

/**
 * Optional Parameters.
 */
export interface JobResumeOptionalParams extends msRest.RequestOptionsBase {
  /**
   * Identifies this specific client request.
   */
  clientRequestId?: string;
}

/**
 * Optional Parameters.
 */
export interface JobListByAutomationAccountNextOptionalParams extends msRest.RequestOptionsBase {
  /**
   * The filter to apply on the operation.
   */
  filter?: string;
  /**
   * Identifies this specific client request.
   */
  clientRequestId?: string;
}

/**
 * Optional Parameters.
 */
export interface JobStreamGetOptionalParams extends msRest.RequestOptionsBase {
  /**
   * Identifies this specific client request.
   */
  clientRequestId?: string;
}

/**
 * Optional Parameters.
 */
export interface JobStreamListByJobOptionalParams extends msRest.RequestOptionsBase {
  /**
   * The filter to apply on the operation.
   */
  filter?: string;
  /**
   * Identifies this specific client request.
   */
  clientRequestId?: string;
}

/**
 * Optional Parameters.
 */
export interface JobStreamListByJobNextOptionalParams extends msRest.RequestOptionsBase {
  /**
   * The filter to apply on the operation.
   */
  filter?: string;
  /**
   * Identifies this specific client request.
   */
  clientRequestId?: string;
}

/**
 * An interface representing AutomationClientOptions.
 */
export interface AutomationClientOptions extends AzureServiceClientOptions {
  baseUri?: string;
}

/**
 * Defines headers for ReplaceContent operation.
 */
export interface RunbookDraftReplaceContentHeaders {
  /**
   * URL to query for status of the operation.
   */
  location: string;
}

/**
 * Defines headers for Publish operation.
 */
export interface RunbookPublishHeaders {
  /**
   * URL to query for status of the operation.
   */
  location: string;
}

/**
 * @interface
 * The response model for the list runbook operation.
 * @extends Array<Runbook>
 */
export interface RunbookListResult extends Array<Runbook> {
  /**
   * Gets or sets the next link.
   */
  nextLink?: string;
}

/**
 * @interface
 * The response model for the list job stream operation.
 * @extends Array<JobStream>
 */
export interface JobStreamListResult extends Array<JobStream> {
  /**
   * Gets or sets the next link.
   */
  nextLink?: string;
}

/**
 * @interface
 * The response model for the list account operation.
 * @extends Array<AutomationAccount>
 */
export interface AutomationAccountListResult extends Array<AutomationAccount> {
  /**
   * Gets or sets the next link.
   */
  nextLink?: string;
}

/**
 * @interface
 * The response model for the list of Automation operations
 * @extends Array<Operation>
 */
export interface OperationListResult extends Array<Operation> {
}

/**
 * @interface
 * The response model for the list statistics operation.
 * @extends Array<Statistics>
 */
export interface StatisticsListResult extends Array<Statistics> {
}

/**
 * @interface
 * The response model for the get usage operation.
 * @extends Array<Usage>
 */
export interface UsageListResult extends Array<Usage> {
}

/**
 * @interface
 * The response model for the list job operation.
 * @extends Array<JobCollectionItem>
 */
export interface JobListResultV2 extends Array<JobCollectionItem> {
  /**
   * The  link to the next page.
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly nextLink?: string;
}

/**
 * Defines values for JobStreamType.
 * Possible values include: 'Progress', 'Output', 'Warning', 'Error', 'Debug', 'Verbose', 'Any'
 * @readonly
 * @enum {string}
 */
export type JobStreamType = 'Progress' | 'Output' | 'Warning' | 'Error' | 'Debug' | 'Verbose' | 'Any';

/**
 * Defines values for RunbookTypeEnum.
 * Possible values include: 'Script', 'Graph', 'PowerShellWorkflow', 'PowerShell',
 * 'GraphPowerShellWorkflow', 'GraphPowerShell'
 * @readonly
 * @enum {string}
 */
export type RunbookTypeEnum = 'Script' | 'Graph' | 'PowerShellWorkflow' | 'PowerShell' | 'GraphPowerShellWorkflow' | 'GraphPowerShell';

/**
 * Defines values for RunbookState.
 * Possible values include: 'New', 'Edit', 'Published'
 * @readonly
 * @enum {string}
 */
export type RunbookState = 'New' | 'Edit' | 'Published';

/**
 * Defines values for RunbookProvisioningState.
 * Possible values include: 'Succeeded'
 * @readonly
 * @enum {string}
 */
export type RunbookProvisioningState = 'Succeeded';

/**
 * Defines values for HttpStatusCode.
 * Possible values include: 'Continue', 'SwitchingProtocols', 'OK', 'Created', 'Accepted',
 * 'NonAuthoritativeInformation', 'NoContent', 'ResetContent', 'PartialContent', 'MultipleChoices',
 * 'Ambiguous', 'MovedPermanently', 'Moved', 'Found', 'Redirect', 'SeeOther', 'RedirectMethod',
 * 'NotModified', 'UseProxy', 'Unused', 'TemporaryRedirect', 'RedirectKeepVerb', 'BadRequest',
 * 'Unauthorized', 'PaymentRequired', 'Forbidden', 'NotFound', 'MethodNotAllowed', 'NotAcceptable',
 * 'ProxyAuthenticationRequired', 'RequestTimeout', 'Conflict', 'Gone', 'LengthRequired',
 * 'PreconditionFailed', 'RequestEntityTooLarge', 'RequestUriTooLong', 'UnsupportedMediaType',
 * 'RequestedRangeNotSatisfiable', 'ExpectationFailed', 'UpgradeRequired', 'InternalServerError',
 * 'NotImplemented', 'BadGateway', 'ServiceUnavailable', 'GatewayTimeout',
 * 'HttpVersionNotSupported'
 * @readonly
 * @enum {string}
 */
export type HttpStatusCode = 'Continue' | 'SwitchingProtocols' | 'OK' | 'Created' | 'Accepted' | 'NonAuthoritativeInformation' | 'NoContent' | 'ResetContent' | 'PartialContent' | 'MultipleChoices' | 'Ambiguous' | 'MovedPermanently' | 'Moved' | 'Found' | 'Redirect' | 'SeeOther' | 'RedirectMethod' | 'NotModified' | 'UseProxy' | 'Unused' | 'TemporaryRedirect' | 'RedirectKeepVerb' | 'BadRequest' | 'Unauthorized' | 'PaymentRequired' | 'Forbidden' | 'NotFound' | 'MethodNotAllowed' | 'NotAcceptable' | 'ProxyAuthenticationRequired' | 'RequestTimeout' | 'Conflict' | 'Gone' | 'LengthRequired' | 'PreconditionFailed' | 'RequestEntityTooLarge' | 'RequestUriTooLong' | 'UnsupportedMediaType' | 'RequestedRangeNotSatisfiable' | 'ExpectationFailed' | 'UpgradeRequired' | 'InternalServerError' | 'NotImplemented' | 'BadGateway' | 'ServiceUnavailable' | 'GatewayTimeout' | 'HttpVersionNotSupported';

/**
 * Defines values for SkuNameEnum.
 * Possible values include: 'Free', 'Basic'
 * @readonly
 * @enum {string}
 */
export type SkuNameEnum = 'Free' | 'Basic';

/**
 * Defines values for AutomationAccountState.
 * Possible values include: 'Ok', 'Unavailable', 'Suspended'
 * @readonly
 * @enum {string}
 */
export type AutomationAccountState = 'Ok' | 'Unavailable' | 'Suspended';

/**
 * Defines values for AutomationKeyName.
 * Possible values include: 'Primary', 'Secondary'
 * @readonly
 * @enum {string}
 */
export type AutomationKeyName = 'Primary' | 'Secondary';

/**
 * Defines values for AutomationKeyPermissions.
 * Possible values include: 'Read', 'Full'
 * @readonly
 * @enum {string}
 */
export type AutomationKeyPermissions = 'Read' | 'Full';

/**
 * Defines values for JobStatus.
 * Possible values include: 'New', 'Activating', 'Running', 'Completed', 'Failed', 'Stopped',
 * 'Blocked', 'Suspended', 'Disconnected', 'Suspending', 'Stopping', 'Resuming', 'Removing'
 * @readonly
 * @enum {string}
 */
export type JobStatus = 'New' | 'Activating' | 'Running' | 'Completed' | 'Failed' | 'Stopped' | 'Blocked' | 'Suspended' | 'Disconnected' | 'Suspending' | 'Stopping' | 'Resuming' | 'Removing';

/**
 * Defines values for JobProvisioningState.
 * Possible values include: 'Failed', 'Succeeded', 'Suspended', 'Processing'
 * @readonly
 * @enum {string}
 */
export type JobProvisioningState = 'Failed' | 'Succeeded' | 'Suspended' | 'Processing';

/**
 * Contains response data for the getContent operation.
 */
export type RunbookDraftGetContentResponse = {
  /**
   * BROWSER ONLY
   *
   * The response body as a browser Blob.
   * Always undefined in node.js.
   */
  blobBody?: Promise<Blob>;

  /**
   * NODEJS ONLY
   *
   * The response body as a node.js Readable stream.
   * Always undefined in the browser.
   */
  readableStreamBody?: NodeJS.ReadableStream;

  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse;
};

/**
 * Contains response data for the replaceContent operation.
 */
export type RunbookDraftReplaceContentResponse = RunbookDraftReplaceContentHeaders & {
  /**
   * BROWSER ONLY
   *
   * The response body as a browser Blob.
   * Always undefined in node.js.
   */
  blobBody?: Promise<Blob>;

  /**
   * NODEJS ONLY
   *
   * The response body as a node.js Readable stream.
   * Always undefined in the browser.
   */
  readableStreamBody?: NodeJS.ReadableStream;

  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The parsed HTTP response headers.
       */
      parsedHeaders: RunbookDraftReplaceContentHeaders;
    };
};

/**
 * Contains response data for the get operation.
 */
export type RunbookDraftGetResponse = RunbookDraft & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: RunbookDraft;
    };
};

/**
 * Contains response data for the undoEdit operation.
 */
export type RunbookDraftUndoEditResponse = RunbookDraftUndoEditResult & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: RunbookDraftUndoEditResult;
    };
};

/**
 * Contains response data for the publish operation.
 */
export type RunbookPublishResponse = RunbookPublishHeaders & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The parsed HTTP response headers.
       */
      parsedHeaders: RunbookPublishHeaders;
    };
};

/**
 * Contains response data for the getContent operation.
 */
export type RunbookGetContentResponse = {
  /**
   * BROWSER ONLY
   *
   * The response body as a browser Blob.
   * Always undefined in node.js.
   */
  blobBody?: Promise<Blob>;

  /**
   * NODEJS ONLY
   *
   * The response body as a node.js Readable stream.
   * Always undefined in the browser.
   */
  readableStreamBody?: NodeJS.ReadableStream;

  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse;
};

/**
 * Contains response data for the get operation.
 */
export type RunbookGetResponse = Runbook & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: Runbook;
    };
};

/**
 * Contains response data for the createOrUpdate operation.
 */
export type RunbookCreateOrUpdateResponse = Runbook & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: Runbook;
    };
};

/**
 * Contains response data for the update operation.
 */
export type RunbookUpdateResponse = Runbook & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: Runbook;
    };
};

/**
 * Contains response data for the listByAutomationAccount operation.
 */
export type RunbookListByAutomationAccountResponse = RunbookListResult & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: RunbookListResult;
    };
};

/**
 * Contains response data for the listByAutomationAccountNext operation.
 */
export type RunbookListByAutomationAccountNextResponse = RunbookListResult & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: RunbookListResult;
    };
};

/**
 * Contains response data for the get operation.
 */
export type TestJobStreamsGetResponse = JobStream & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: JobStream;
    };
};

/**
 * Contains response data for the listByTestJob operation.
 */
export type TestJobStreamsListByTestJobResponse = JobStreamListResult & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: JobStreamListResult;
    };
};

/**
 * Contains response data for the listByTestJobNext operation.
 */
export type TestJobStreamsListByTestJobNextResponse = JobStreamListResult & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: JobStreamListResult;
    };
};

/**
 * Contains response data for the create operation.
 */
export type TestJobCreateResponse = TestJob & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: TestJob;
    };
};

/**
 * Contains response data for the get operation.
 */
export type TestJobGetResponse = TestJob & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: TestJob;
    };
};

/**
 * Contains response data for the update operation.
 */
export type AutomationAccountUpdateResponse = AutomationAccount & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: AutomationAccount;
    };
};

/**
 * Contains response data for the createOrUpdate operation.
 */
export type AutomationAccountCreateOrUpdateResponse = AutomationAccount & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: AutomationAccount;
    };
};

/**
 * Contains response data for the get operation.
 */
export type AutomationAccountGetResponse = AutomationAccount & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: AutomationAccount;
    };
};

/**
 * Contains response data for the listByResourceGroup operation.
 */
export type AutomationAccountListByResourceGroupResponse = AutomationAccountListResult & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: AutomationAccountListResult;
    };
};

/**
 * Contains response data for the list operation.
 */
export type AutomationAccountListResponse = AutomationAccountListResult & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: AutomationAccountListResult;
    };
};

/**
 * Contains response data for the listByResourceGroupNext operation.
 */
export type AutomationAccountListByResourceGroupNextResponse = AutomationAccountListResult & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: AutomationAccountListResult;
    };
};

/**
 * Contains response data for the listNext operation.
 */
export type AutomationAccountListNextResponse = AutomationAccountListResult & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: AutomationAccountListResult;
    };
};

/**
 * Contains response data for the list operation.
 */
export type OperationsListResponse = OperationListResult & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: OperationListResult;
    };
};

/**
 * Contains response data for the listByAutomationAccount operation.
 */
export type StatisticsListByAutomationAccountResponse = StatisticsListResult & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: StatisticsListResult;
    };
};

/**
 * Contains response data for the listByAutomationAccount operation.
 */
export type UsagesListByAutomationAccountResponse = UsageListResult & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: UsageListResult;
    };
};

/**
 * Contains response data for the listByAutomationAccount operation.
 */
export type KeysListByAutomationAccountResponse = KeyListResult & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: KeyListResult;
    };
};

/**
 * Contains response data for the getOutput operation.
 */
export type JobGetOutputResponse = {
  /**
   * BROWSER ONLY
   *
   * The response body as a browser Blob.
   * Always undefined in node.js.
   */
  blobBody?: Promise<Blob>;

  /**
   * NODEJS ONLY
   *
   * The response body as a node.js Readable stream.
   * Always undefined in the browser.
   */
  readableStreamBody?: NodeJS.ReadableStream;

  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse;
};

/**
 * Contains response data for the getRunbookContent operation.
 */
export type JobGetRunbookContentResponse = {
  /**
   * BROWSER ONLY
   *
   * The response body as a browser Blob.
   * Always undefined in node.js.
   */
  blobBody?: Promise<Blob>;

  /**
   * NODEJS ONLY
   *
   * The response body as a node.js Readable stream.
   * Always undefined in the browser.
   */
  readableStreamBody?: NodeJS.ReadableStream;

  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse;
};

/**
 * Contains response data for the get operation.
 */
export type JobGetResponse = Job & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: Job;
    };
};

/**
 * Contains response data for the create operation.
 */
export type JobCreateResponse = Job & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: Job;
    };
};

/**
 * Contains response data for the listByAutomationAccount operation.
 */
export type JobListByAutomationAccountResponse = JobListResultV2 & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: JobListResultV2;
    };
};

/**
 * Contains response data for the listByAutomationAccountNext operation.
 */
export type JobListByAutomationAccountNextResponse = JobListResultV2 & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: JobListResultV2;
    };
};

/**
 * Contains response data for the get operation.
 */
export type JobStreamGetResponse = JobStream & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: JobStream;
    };
};

/**
 * Contains response data for the listByJob operation.
 */
export type JobStreamListByJobResponse = JobStreamListResult & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: JobStreamListResult;
    };
};

/**
 * Contains response data for the listByJobNext operation.
 */
export type JobStreamListByJobNextResponse = JobStreamListResult & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: JobStreamListResult;
    };
};
