/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";
import * as Models from "../models";
import * as Mappers from "../models/environmentSpecificationVersionsMappers";
import * as Parameters from "../models/parameters";
import { AzureMachineLearningWorkspacesContext } from "../azureMachineLearningWorkspacesContext";

/** Class representing a EnvironmentSpecificationVersions. */
export class EnvironmentSpecificationVersions {
  private readonly client: AzureMachineLearningWorkspacesContext;

  /**
   * Create a EnvironmentSpecificationVersions.
   * @param {AzureMachineLearningWorkspacesContext} client Reference to the service client.
   */
  constructor(client: AzureMachineLearningWorkspacesContext) {
    this.client = client;
  }

  /**
   * @param name
   * @param version
   * @param resourceGroupName Name of the resource group in which workspace is located.
   * @param workspaceName Name of Azure Machine Learning workspace.
   * @param [options] The optional parameters
   * @returns Promise<Models.EnvironmentSpecificationVersionsCreateOrUpdateResponse>
   */
  createOrUpdate(name: string, version: string, resourceGroupName: string, workspaceName: string, options?: Models.EnvironmentSpecificationVersionsCreateOrUpdateOptionalParams): Promise<Models.EnvironmentSpecificationVersionsCreateOrUpdateResponse>;
  /**
   * @param name
   * @param version
   * @param resourceGroupName Name of the resource group in which workspace is located.
   * @param workspaceName Name of Azure Machine Learning workspace.
   * @param callback The callback
   */
  createOrUpdate(name: string, version: string, resourceGroupName: string, workspaceName: string, callback: msRest.ServiceCallback<Models.EnvironmentSpecificationVersionResource>): void;
  /**
   * @param name
   * @param version
   * @param resourceGroupName Name of the resource group in which workspace is located.
   * @param workspaceName Name of Azure Machine Learning workspace.
   * @param options The optional parameters
   * @param callback The callback
   */
  createOrUpdate(name: string, version: string, resourceGroupName: string, workspaceName: string, options: Models.EnvironmentSpecificationVersionsCreateOrUpdateOptionalParams, callback: msRest.ServiceCallback<Models.EnvironmentSpecificationVersionResource>): void;
  createOrUpdate(name: string, version: string, resourceGroupName: string, workspaceName: string, options?: Models.EnvironmentSpecificationVersionsCreateOrUpdateOptionalParams | msRest.ServiceCallback<Models.EnvironmentSpecificationVersionResource>, callback?: msRest.ServiceCallback<Models.EnvironmentSpecificationVersionResource>): Promise<Models.EnvironmentSpecificationVersionsCreateOrUpdateResponse> {
    return this.client.sendOperationRequest(
      {
        name,
        version,
        resourceGroupName,
        workspaceName,
        options
      },
      createOrUpdateOperationSpec,
      callback) as Promise<Models.EnvironmentSpecificationVersionsCreateOrUpdateResponse>;
  }

  /**
   * @summary Get version.
   * @param name Container name.
   * @param version Version identifier.
   * @param resourceGroupName Name of the resource group in which workspace is located.
   * @param workspaceName Name of Azure Machine Learning workspace.
   * @param [options] The optional parameters
   * @returns Promise<Models.EnvironmentSpecificationVersionsGetResponse>
   */
  get(name: string, version: string, resourceGroupName: string, workspaceName: string, options?: msRest.RequestOptionsBase): Promise<Models.EnvironmentSpecificationVersionsGetResponse>;
  /**
   * @param name Container name.
   * @param version Version identifier.
   * @param resourceGroupName Name of the resource group in which workspace is located.
   * @param workspaceName Name of Azure Machine Learning workspace.
   * @param callback The callback
   */
  get(name: string, version: string, resourceGroupName: string, workspaceName: string, callback: msRest.ServiceCallback<Models.EnvironmentSpecificationVersionResource>): void;
  /**
   * @param name Container name.
   * @param version Version identifier.
   * @param resourceGroupName Name of the resource group in which workspace is located.
   * @param workspaceName Name of Azure Machine Learning workspace.
   * @param options The optional parameters
   * @param callback The callback
   */
  get(name: string, version: string, resourceGroupName: string, workspaceName: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.EnvironmentSpecificationVersionResource>): void;
  get(name: string, version: string, resourceGroupName: string, workspaceName: string, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.EnvironmentSpecificationVersionResource>, callback?: msRest.ServiceCallback<Models.EnvironmentSpecificationVersionResource>): Promise<Models.EnvironmentSpecificationVersionsGetResponse> {
    return this.client.sendOperationRequest(
      {
        name,
        version,
        resourceGroupName,
        workspaceName,
        options
      },
      getOperationSpec,
      callback) as Promise<Models.EnvironmentSpecificationVersionsGetResponse>;
  }

  /**
   * @summary Delete version.
   * @param name Container name.
   * @param version Version identifier.
   * @param resourceGroupName Name of the resource group in which workspace is located.
   * @param workspaceName Name of Azure Machine Learning workspace.
   * @param [options] The optional parameters
   * @returns Promise<msRest.RestResponse>
   */
  deleteMethod(name: string, version: string, resourceGroupName: string, workspaceName: string, options?: msRest.RequestOptionsBase): Promise<msRest.RestResponse>;
  /**
   * @param name Container name.
   * @param version Version identifier.
   * @param resourceGroupName Name of the resource group in which workspace is located.
   * @param workspaceName Name of Azure Machine Learning workspace.
   * @param callback The callback
   */
  deleteMethod(name: string, version: string, resourceGroupName: string, workspaceName: string, callback: msRest.ServiceCallback<void>): void;
  /**
   * @param name Container name.
   * @param version Version identifier.
   * @param resourceGroupName Name of the resource group in which workspace is located.
   * @param workspaceName Name of Azure Machine Learning workspace.
   * @param options The optional parameters
   * @param callback The callback
   */
  deleteMethod(name: string, version: string, resourceGroupName: string, workspaceName: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<void>): void;
  deleteMethod(name: string, version: string, resourceGroupName: string, workspaceName: string, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<void>, callback?: msRest.ServiceCallback<void>): Promise<msRest.RestResponse> {
    return this.client.sendOperationRequest(
      {
        name,
        version,
        resourceGroupName,
        workspaceName,
        options
      },
      deleteMethodOperationSpec,
      callback);
  }

  /**
   * @param name
   * @param resourceGroupName Name of the resource group in which workspace is located.
   * @param workspaceName Name of Azure Machine Learning workspace.
   * @param [options] The optional parameters
   * @returns Promise<Models.EnvironmentSpecificationVersionsListResponse>
   */
  list(name: string, resourceGroupName: string, workspaceName: string, options?: Models.EnvironmentSpecificationVersionsListOptionalParams): Promise<Models.EnvironmentSpecificationVersionsListResponse>;
  /**
   * @param name
   * @param resourceGroupName Name of the resource group in which workspace is located.
   * @param workspaceName Name of Azure Machine Learning workspace.
   * @param callback The callback
   */
  list(name: string, resourceGroupName: string, workspaceName: string, callback: msRest.ServiceCallback<Models.EnvironmentSpecificationVersionResourceArmPaginatedResult>): void;
  /**
   * @param name
   * @param resourceGroupName Name of the resource group in which workspace is located.
   * @param workspaceName Name of Azure Machine Learning workspace.
   * @param options The optional parameters
   * @param callback The callback
   */
  list(name: string, resourceGroupName: string, workspaceName: string, options: Models.EnvironmentSpecificationVersionsListOptionalParams, callback: msRest.ServiceCallback<Models.EnvironmentSpecificationVersionResourceArmPaginatedResult>): void;
  list(name: string, resourceGroupName: string, workspaceName: string, options?: Models.EnvironmentSpecificationVersionsListOptionalParams | msRest.ServiceCallback<Models.EnvironmentSpecificationVersionResourceArmPaginatedResult>, callback?: msRest.ServiceCallback<Models.EnvironmentSpecificationVersionResourceArmPaginatedResult>): Promise<Models.EnvironmentSpecificationVersionsListResponse> {
    return this.client.sendOperationRequest(
      {
        name,
        resourceGroupName,
        workspaceName,
        options
      },
      listOperationSpec,
      callback) as Promise<Models.EnvironmentSpecificationVersionsListResponse>;
  }

  /**
   * @param nextPageLink The NextLink from the previous successful call to List operation.
   * @param [options] The optional parameters
   * @returns Promise<Models.EnvironmentSpecificationVersionsListNextResponse>
   */
  listNext(nextPageLink: string, options?: Models.EnvironmentSpecificationVersionsListNextOptionalParams): Promise<Models.EnvironmentSpecificationVersionsListNextResponse>;
  /**
   * @param nextPageLink The NextLink from the previous successful call to List operation.
   * @param callback The callback
   */
  listNext(nextPageLink: string, callback: msRest.ServiceCallback<Models.EnvironmentSpecificationVersionResourceArmPaginatedResult>): void;
  /**
   * @param nextPageLink The NextLink from the previous successful call to List operation.
   * @param options The optional parameters
   * @param callback The callback
   */
  listNext(nextPageLink: string, options: Models.EnvironmentSpecificationVersionsListNextOptionalParams, callback: msRest.ServiceCallback<Models.EnvironmentSpecificationVersionResourceArmPaginatedResult>): void;
  listNext(nextPageLink: string, options?: Models.EnvironmentSpecificationVersionsListNextOptionalParams | msRest.ServiceCallback<Models.EnvironmentSpecificationVersionResourceArmPaginatedResult>, callback?: msRest.ServiceCallback<Models.EnvironmentSpecificationVersionResourceArmPaginatedResult>): Promise<Models.EnvironmentSpecificationVersionsListNextResponse> {
    return this.client.sendOperationRequest(
      {
        nextPageLink,
        options
      },
      listNextOperationSpec,
      callback) as Promise<Models.EnvironmentSpecificationVersionsListNextResponse>;
  }
}

// Operation Specifications
const serializer = new msRest.Serializer(Mappers);
const createOrUpdateOperationSpec: msRest.OperationSpec = {
  httpMethod: "PUT",
  path: "subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.MachineLearningServices/workspaces/{workspaceName}/environments/{name}/versions/{version}",
  urlParameters: [
    Parameters.name,
    Parameters.version0,
    Parameters.subscriptionId,
    Parameters.resourceGroupName,
    Parameters.workspaceName
  ],
  queryParameters: [
    Parameters.apiVersion
  ],
  headerParameters: [
    Parameters.acceptLanguage
  ],
  requestBody: {
    parameterPath: [
      "options",
      "body"
    ],
    mapper: Mappers.EnvironmentSpecificationVersionResource
  },
  responses: {
    200: {
      bodyMapper: Mappers.EnvironmentSpecificationVersionResource
    },
    201: {
      bodyMapper: Mappers.EnvironmentSpecificationVersionResource
    },
    default: {
      bodyMapper: Mappers.MachineLearningServiceError
    }
  },
  serializer
};

const getOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.MachineLearningServices/workspaces/{workspaceName}/environments/{name}/versions/{version}",
  urlParameters: [
    Parameters.name,
    Parameters.version0,
    Parameters.subscriptionId,
    Parameters.resourceGroupName,
    Parameters.workspaceName
  ],
  queryParameters: [
    Parameters.apiVersion
  ],
  headerParameters: [
    Parameters.acceptLanguage
  ],
  responses: {
    200: {
      bodyMapper: Mappers.EnvironmentSpecificationVersionResource
    },
    default: {
      bodyMapper: Mappers.MachineLearningServiceError
    }
  },
  serializer
};

const deleteMethodOperationSpec: msRest.OperationSpec = {
  httpMethod: "DELETE",
  path: "subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.MachineLearningServices/workspaces/{workspaceName}/environments/{name}/versions/{version}",
  urlParameters: [
    Parameters.name,
    Parameters.version0,
    Parameters.subscriptionId,
    Parameters.resourceGroupName,
    Parameters.workspaceName
  ],
  queryParameters: [
    Parameters.apiVersion
  ],
  headerParameters: [
    Parameters.acceptLanguage
  ],
  responses: {
    200: {},
    204: {},
    default: {
      bodyMapper: Mappers.MachineLearningServiceError
    }
  },
  serializer
};

const listOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.MachineLearningServices/workspaces/{workspaceName}/environments/{name}/versions",
  urlParameters: [
    Parameters.name,
    Parameters.subscriptionId,
    Parameters.resourceGroupName,
    Parameters.workspaceName
  ],
  queryParameters: [
    Parameters.apiVersion,
    Parameters.orderby1,
    Parameters.top,
    Parameters.skiptoken
  ],
  headerParameters: [
    Parameters.acceptLanguage
  ],
  responses: {
    200: {
      bodyMapper: Mappers.EnvironmentSpecificationVersionResourceArmPaginatedResult
    },
    default: {
      bodyMapper: Mappers.MachineLearningServiceError
    }
  },
  serializer
};

const listNextOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  baseUrl: "https://management.azure.com",
  path: "{nextLink}",
  urlParameters: [
    Parameters.nextPageLink
  ],
  queryParameters: [
    Parameters.apiVersion,
    Parameters.orderby1,
    Parameters.top,
    Parameters.skiptoken
  ],
  headerParameters: [
    Parameters.acceptLanguage
  ],
  responses: {
    200: {
      bodyMapper: Mappers.EnvironmentSpecificationVersionResourceArmPaginatedResult
    },
    default: {
      bodyMapper: Mappers.MachineLearningServiceError
    }
  },
  serializer
};
