/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import { BaseResource, CloudError, AzureServiceClientOptions } from "@azure/ms-rest-azure-js";
import * as msRest from "@azure/ms-rest-js";

export { BaseResource, CloudError };

/**
 * Identity for the Automanage account.
 */
export interface AccountIdentity {
  /**
   * The principal id of Automanage account identity.
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly principalId?: string;
  /**
   * The tenant id associated with the Automanage account.
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly tenantId?: string;
  /**
   * The type of identity used for the Automanage account. Currently, the only supported type is
   * 'SystemAssigned', which implicitly creates an identity. Possible values include:
   * 'SystemAssigned', 'None'
   */
  type?: ResourceIdentityType;
}

/**
 * Common fields that are returned in the response for all Azure Resource Manager resources
 */
export interface Resource extends BaseResource {
  /**
   * Fully qualified resource ID for the resource. Ex -
   * /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly id?: string;
  /**
   * The name of the resource
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly name?: string;
  /**
   * The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or
   * "Microsoft.Storage/storageAccounts"
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly type?: string;
}

/**
 * The resource model definition for an Azure Resource Manager tracked top level resource
 */
export interface TrackedResource extends Resource {
  /**
   * Resource tags.
   */
  tags?: { [propertyName: string]: string };
  /**
   * The geo-location where the resource lives
   */
  location: string;
}

/**
 * Definition of the Automanage account.
 */
export interface Account extends TrackedResource {
  /**
   * The identity of the Automanage account.
   */
  identity?: AccountIdentity;
}

/**
 * Represents an update resource
 */
export interface UpdateResource {
  /**
   * The tags of the resource.
   */
  tags?: { [propertyName: string]: string };
}

/**
 * Definition of the Automanage account.
 */
export interface AccountUpdate extends UpdateResource {
  /**
   * The identity of the Automanage account.
   */
  identity?: AccountIdentity;
}

/**
 * Data related to assignment profile compliance.
 */
export interface ConfigurationProfileAssignmentCompliance {
  /**
   * The status of the assignment profile compliance. Possible values include: 'Succeeded',
   * 'Failed', 'Created'
   */
  status: ComplianceStatus;
  /**
   * Describes unknown properties. The value of an unknown property can be of "any" type.
   */
  [property: string]: any;
}

/**
 * Automanage configuration profile assignment properties.
 */
export interface ConfigurationProfileAssignmentProperties {
  /**
   * A value indicating configuration profile. Possible values include: 'Azure virtual machine best
   * practices – Dev/Test', 'Azure virtual machine best practices – Production'
   */
  configurationProfile?: ConfigurationProfile;
  /**
   * The target VM resource URI
   */
  targetId?: string;
  /**
   * The Automanage account ARM Resource URI
   */
  accountId?: string;
  /**
   * The configuration profile custom preferences ARM resource URI
   */
  configurationProfilePreferenceId?: string;
  /**
   * The state of onboarding, which only appears in the response. Possible values include:
   * 'Succeeded', 'Failed', 'Created'
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly provisioningState?: ProvisioningState;
  /**
   * The configuration setting for the configuration profile.
   */
  compliance?: ConfigurationProfileAssignmentCompliance;
}

/**
 * The resource model definition for an Azure Resource Manager proxy resource. It will have
 * everything other than required location and tags
 */
export interface ProxyResource extends Resource {
}

/**
 * Configuration profile assignment is an association between a VM and automanage profile
 * configuration.
 */
export interface ConfigurationProfileAssignment extends ProxyResource {
  /**
   * Properties of the configuration profile assignment.
   */
  properties?: ConfigurationProfileAssignmentProperties;
}

/**
 * Automanage configuration profile VM Backup preferences.
 */
export interface ConfigurationProfilePreferenceVmBackup {
  /**
   * TimeZone optional input as string. For example: Pacific Standard Time
   */
  timeZone?: string;
  /**
   * Instant RP retention policy range in days
   */
  instantRpRetentionRangeInDays?: number;
  /**
   * Retention policy with the details on backup copy retention ranges.
   */
  retentionPolicy?: string;
  /**
   * Backup schedule specified as part of backup policy.
   */
  schedulePolicy?: string;
}

/**
 * Automanage configuration profile Antimalware preferences.
 */
export interface ConfigurationProfilePreferenceAntimalware {
  /**
   * Enables or disables Real Time Protection. Possible values include: 'True', 'False'
   */
  enableRealTimeProtection?: EnableRealTimeProtection;
  /**
   * Extensions, Paths and Processes that must be excluded from scan
   */
  exclusions?: any;
  /**
   * Enables or disables a periodic scan for antimalware. Possible values include: 'True', 'False'
   */
  runScheduledScan?: RunScheduledScan;
  /**
   * Type of scheduled scan. Possible values include: 'Quick', 'Full'
   */
  scanType?: ScanType;
  /**
   * Schedule scan settings day
   */
  scanDay?: string;
  /**
   * Schedule scan settings time
   */
  scanTimeInMinutes?: string;
}

/**
 * Automanage configuration profile preference properties.
 */
export interface ConfigurationProfilePreferenceProperties {
  /**
   * The custom preferences for Azure VM Backup.
   */
  vmBackup?: ConfigurationProfilePreferenceVmBackup;
  /**
   * The custom preferences for Azure Antimalware.
   */
  antimalware?: ConfigurationProfilePreferenceAntimalware;
}

/**
 * Metadata pertaining to creation and last modification of the resource.
 */
export interface SystemData {
  /**
   * The identity that created the resource.
   */
  createdBy?: string;
  /**
   * The type of identity that created the resource. Possible values include: 'User',
   * 'Application', 'ManagedIdentity', 'Key'
   */
  createdByType?: CreatedByType;
  /**
   * The timestamp of resource creation (UTC).
   */
  createdAt?: Date;
  /**
   * The identity that last modified the resource.
   */
  lastModifiedBy?: string;
  /**
   * The type of identity that last modified the resource. Possible values include: 'User',
   * 'Application', 'ManagedIdentity', 'Key'
   */
  lastModifiedByType?: CreatedByType;
  /**
   * The type of identity that last modified the resource.
   */
  lastModifiedAt?: Date;
}

/**
 * Definition of the configuration profile preference.
 */
export interface ConfigurationProfilePreference extends TrackedResource {
  /**
   * Properties of the configuration profile preference.
   */
  properties?: ConfigurationProfilePreferenceProperties;
  /**
   * Metadata pertaining to creation and last modification of the resource.
   */
  systemData?: SystemData;
}

/**
 * Definition of the configuration profile preference.
 */
export interface ConfigurationProfilePreferenceUpdate extends UpdateResource {
  /**
   * Properties of the configuration profile preference.
   */
  properties?: ConfigurationProfilePreferenceProperties;
}

/**
 * The resource model definition for an Azure Resource Manager resource with an etag.
 */
export interface AzureEntityResource extends Resource {
  /**
   * Resource Etag.
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly etag?: string;
}

/**
 * The resource management error additional info.
 */
export interface ErrorAdditionalInfo {
  /**
   * The additional info type.
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly type?: string;
  /**
   * The additional info.
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly info?: any;
}

/**
 * The error detail.
 */
export interface ErrorDetail {
  /**
   * The error code.
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly code?: string;
  /**
   * The error message.
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly message?: string;
  /**
   * The error target.
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly target?: string;
  /**
   * The error details.
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly details?: ErrorDetail[];
  /**
   * The error additional info.
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly additionalInfo?: ErrorAdditionalInfo[];
}

/**
 * Common error response for all Azure Resource Manager APIs to return error details for failed
 * operations. (This also follows the OData error response format.).
 * @summary Error response
 */
export interface ErrorResponse {
  /**
   * The error object.
   */
  error?: ErrorDetail;
}

/**
 * Localized display information for this particular operation.
 */
export interface OperationDisplay {
  /**
   * The localized friendly form of the resource provider name, e.g. "Microsoft Monitoring
   * Insights" or "Microsoft Compute".
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly provider?: string;
  /**
   * The localized friendly name of the resource type related to this operation. E.g. "Virtual
   * Machines" or "Job Schedule Collections".
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly resource?: string;
  /**
   * The concise, localized friendly name for the operation; suitable for dropdowns. E.g. "Create
   * or Update Virtual Machine", "Restart Virtual Machine".
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly operation?: string;
  /**
   * The short, localized friendly description of the operation; suitable for tool tips and
   * detailed views.
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly description?: string;
}

/**
 * Details of a REST API operation, returned from the Resource Provider Operations API
 */
export interface Operation {
  /**
   * The name of the operation, as per Resource-Based Access Control (RBAC). Examples:
   * "Microsoft.Compute/virtualMachines/write", "Microsoft.Compute/virtualMachines/capture/action"
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly name?: string;
  /**
   * Whether the operation applies to data-plane. This is "true" for data-plane operations and
   * "false" for ARM/control-plane operations.
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly isDataAction?: boolean;
  /**
   * Localized display information for this particular operation.
   */
  display?: OperationDisplay;
  /**
   * The intended executor of the operation; as in Resource Based Access Control (RBAC) and audit
   * logs UX. Default value is "user,system". Possible values include: 'user', 'system',
   * 'user,system'
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly origin?: Origin;
  /**
   * Enum. Indicates the action type. "Internal" refers to actions that are for internal only APIs.
   * Possible values include: 'Internal'
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly actionType?: ActionType;
}

/**
 * An interface representing AutomanageClientOptions.
 */
export interface AutomanageClientOptions extends AzureServiceClientOptions {
  baseUri?: string;
}

/**
 * @interface
 * The response of the list Account operation.
 * @extends Array<Account>
 */
export interface AccountList extends Array<Account> {
}

/**
 * @interface
 * The response of the list configuration profile assignment operation.
 * @extends Array<ConfigurationProfileAssignment>
 */
export interface ConfigurationProfileAssignmentList extends Array<ConfigurationProfileAssignment> {
}

/**
 * @interface
 * The response of the list ConfigurationProfilePreference operation.
 * @extends Array<ConfigurationProfilePreference>
 */
export interface ConfigurationProfilePreferenceList extends Array<ConfigurationProfilePreference> {
}

/**
 * @interface
 * A list of REST API operations supported by an Azure Resource Provider. It contains an URL link
 * to get the next set of results.
 * @extends Array<Operation>
 */
export interface OperationListResult extends Array<Operation> {
  /**
   * URL to get the next set of operation list results (if there are any).
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly nextLink?: string;
}

/**
 * Defines values for ResourceIdentityType.
 * Possible values include: 'SystemAssigned', 'None'
 * @readonly
 * @enum {string}
 */
export type ResourceIdentityType = 'SystemAssigned' | 'None';

/**
 * Defines values for ConfigurationProfile.
 * Possible values include: 'Azure virtual machine best practices – Dev/Test', 'Azure virtual
 * machine best practices – Production'
 * @readonly
 * @enum {string}
 */
export type ConfigurationProfile = 'Azure virtual machine best practices – Dev/Test' | 'Azure virtual machine best practices – Production';

/**
 * Defines values for ProvisioningState.
 * Possible values include: 'Succeeded', 'Failed', 'Created'
 * @readonly
 * @enum {string}
 */
export type ProvisioningState = 'Succeeded' | 'Failed' | 'Created';

/**
 * Defines values for ComplianceStatus.
 * Possible values include: 'Succeeded', 'Failed', 'Created'
 * @readonly
 * @enum {string}
 */
export type ComplianceStatus = 'Succeeded' | 'Failed' | 'Created';

/**
 * Defines values for EnableRealTimeProtection.
 * Possible values include: 'True', 'False'
 * @readonly
 * @enum {string}
 */
export type EnableRealTimeProtection = 'True' | 'False';

/**
 * Defines values for RunScheduledScan.
 * Possible values include: 'True', 'False'
 * @readonly
 * @enum {string}
 */
export type RunScheduledScan = 'True' | 'False';

/**
 * Defines values for ScanType.
 * Possible values include: 'Quick', 'Full'
 * @readonly
 * @enum {string}
 */
export type ScanType = 'Quick' | 'Full';

/**
 * Defines values for CreatedByType.
 * Possible values include: 'User', 'Application', 'ManagedIdentity', 'Key'
 * @readonly
 * @enum {string}
 */
export type CreatedByType = 'User' | 'Application' | 'ManagedIdentity' | 'Key';

/**
 * Defines values for Origin.
 * Possible values include: 'user', 'system', 'user,system'
 * @readonly
 * @enum {string}
 */
export type Origin = 'user' | 'system' | 'user,system';

/**
 * Defines values for ActionType.
 * Possible values include: 'Internal'
 * @readonly
 * @enum {string}
 */
export type ActionType = 'Internal';

/**
 * Contains response data for the createOrUpdate operation.
 */
export type AccountsCreateOrUpdateResponse = Account & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: Account;
    };
};

/**
 * Contains response data for the get operation.
 */
export type AccountsGetResponse = Account & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: Account;
    };
};

/**
 * Contains response data for the update operation.
 */
export type AccountsUpdateResponse = Account & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: Account;
    };
};

/**
 * Contains response data for the listByResourceGroup operation.
 */
export type AccountsListByResourceGroupResponse = AccountList & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: AccountList;
    };
};

/**
 * Contains response data for the listBySubscription operation.
 */
export type AccountsListBySubscriptionResponse = AccountList & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: AccountList;
    };
};

/**
 * Contains response data for the createOrUpdate operation.
 */
export type ConfigurationProfileAssignmentsCreateOrUpdateResponse = ConfigurationProfileAssignment & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: ConfigurationProfileAssignment;
    };
};

/**
 * Contains response data for the get operation.
 */
export type ConfigurationProfileAssignmentsGetResponse = ConfigurationProfileAssignment & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: ConfigurationProfileAssignment;
    };
};

/**
 * Contains response data for the list operation.
 */
export type ConfigurationProfileAssignmentsListResponse = ConfigurationProfileAssignmentList & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: ConfigurationProfileAssignmentList;
    };
};

/**
 * Contains response data for the listBySubscription operation.
 */
export type ConfigurationProfileAssignmentsListBySubscriptionResponse = ConfigurationProfileAssignmentList & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: ConfigurationProfileAssignmentList;
    };
};

/**
 * Contains response data for the beginCreateOrUpdate operation.
 */
export type ConfigurationProfileAssignmentsBeginCreateOrUpdateResponse = ConfigurationProfileAssignment & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: ConfigurationProfileAssignment;
    };
};

/**
 * Contains response data for the createOrUpdate operation.
 */
export type ConfigurationProfilePreferencesCreateOrUpdateResponse = ConfigurationProfilePreference & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: ConfigurationProfilePreference;
    };
};

/**
 * Contains response data for the get operation.
 */
export type ConfigurationProfilePreferencesGetResponse = ConfigurationProfilePreference & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: ConfigurationProfilePreference;
    };
};

/**
 * Contains response data for the update operation.
 */
export type ConfigurationProfilePreferencesUpdateResponse = ConfigurationProfilePreference & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: ConfigurationProfilePreference;
    };
};

/**
 * Contains response data for the listByResourceGroup operation.
 */
export type ConfigurationProfilePreferencesListByResourceGroupResponse = ConfigurationProfilePreferenceList & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: ConfigurationProfilePreferenceList;
    };
};

/**
 * Contains response data for the listBySubscription operation.
 */
export type ConfigurationProfilePreferencesListBySubscriptionResponse = ConfigurationProfilePreferenceList & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: ConfigurationProfilePreferenceList;
    };
};

/**
 * Contains response data for the list operation.
 */
export type OperationsListResponse = OperationListResult & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: OperationListResult;
    };
};
