/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";
import * as Models from "../models";
import * as Mappers from "../models/enrollmentAccountRoleAssignmentsMappers";
import * as Parameters from "../models/parameters";
import { BillingManagementClientContext } from "../billingManagementClientContext";

/** Class representing a EnrollmentAccountRoleAssignments. */
export class EnrollmentAccountRoleAssignments {
  private readonly client: BillingManagementClientContext;

  /**
   * Create a EnrollmentAccountRoleAssignments.
   * @param {BillingManagementClientContext} client Reference to the service client.
   */
  constructor(client: BillingManagementClientContext) {
    this.client = client;
  }

  /**
   * Create or update a billing role assignment.
   * @param billingAccountName The ID that uniquely identifies a billing account.
   * @param enrollmentAccountName The ID that uniquely identifies an enrollment account.
   * @param billingRoleAssignmentName The ID that uniquely identifies a role assignment.
   * @param parameters The new or updated billing role assignment.
   * @param [options] The optional parameters
   * @returns Promise<Models.EnrollmentAccountRoleAssignmentsPutResponse>
   */
  put(billingAccountName: string, enrollmentAccountName: string, billingRoleAssignmentName: string, parameters: Models.BillingRoleAssignment, options?: msRest.RequestOptionsBase): Promise<Models.EnrollmentAccountRoleAssignmentsPutResponse>;
  /**
   * @param billingAccountName The ID that uniquely identifies a billing account.
   * @param enrollmentAccountName The ID that uniquely identifies an enrollment account.
   * @param billingRoleAssignmentName The ID that uniquely identifies a role assignment.
   * @param parameters The new or updated billing role assignment.
   * @param callback The callback
   */
  put(billingAccountName: string, enrollmentAccountName: string, billingRoleAssignmentName: string, parameters: Models.BillingRoleAssignment, callback: msRest.ServiceCallback<Models.BillingRoleAssignment>): void;
  /**
   * @param billingAccountName The ID that uniquely identifies a billing account.
   * @param enrollmentAccountName The ID that uniquely identifies an enrollment account.
   * @param billingRoleAssignmentName The ID that uniquely identifies a role assignment.
   * @param parameters The new or updated billing role assignment.
   * @param options The optional parameters
   * @param callback The callback
   */
  put(billingAccountName: string, enrollmentAccountName: string, billingRoleAssignmentName: string, parameters: Models.BillingRoleAssignment, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.BillingRoleAssignment>): void;
  put(billingAccountName: string, enrollmentAccountName: string, billingRoleAssignmentName: string, parameters: Models.BillingRoleAssignment, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.BillingRoleAssignment>, callback?: msRest.ServiceCallback<Models.BillingRoleAssignment>): Promise<Models.EnrollmentAccountRoleAssignmentsPutResponse> {
    return this.client.sendOperationRequest(
      {
        billingAccountName,
        enrollmentAccountName,
        billingRoleAssignmentName,
        parameters,
        options
      },
      putOperationSpec,
      callback) as Promise<Models.EnrollmentAccountRoleAssignmentsPutResponse>;
  }
}

// Operation Specifications
const serializer = new msRest.Serializer(Mappers);
const putOperationSpec: msRest.OperationSpec = {
  httpMethod: "PUT",
  path: "providers/Microsoft.Billing/billingAccounts/{billingAccountName}/enrollmentAccounts/{enrollmentAccountName}/billingRoleAssignments/{billingRoleAssignmentName}",
  urlParameters: [
    Parameters.billingAccountName,
    Parameters.enrollmentAccountName,
    Parameters.billingRoleAssignmentName
  ],
  queryParameters: [
    Parameters.apiVersion0
  ],
  headerParameters: [
    Parameters.acceptLanguage
  ],
  requestBody: {
    parameterPath: "parameters",
    mapper: {
      ...Mappers.BillingRoleAssignment,
      required: true
    }
  },
  responses: {
    200: {
      bodyMapper: Mappers.BillingRoleAssignment
    },
    default: {
      bodyMapper: Mappers.ErrorResponse
    }
  },
  serializer
};
