/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import { BaseResource, CloudError, AzureServiceClientOptions } from "@azure/ms-rest-azure-js";
import * as msRest from "@azure/ms-rest-js";

export { BaseResource, CloudError };

/**
 * An Azure resource.
 */
export interface Resource extends BaseResource {
  /**
   * Azure resource Id.
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly id?: string;
  /**
   * Azure resource name. Preferably as a <namespace>-<service>
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly name?: string;
  /**
   * Azure resource type.
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly type?: string;
  /**
   * Location of the resource.
   */
  location?: string;
  /**
   * resource tags.
   */
  tags?: { [propertyName: string]: string };
}

/**
 * An interface representing FalconResourceProperties.
 */
export interface FalconResourceProperties {
  /**
   * Namespace in Falcon
   */
  namespaceName: string;
  /**
   * Service in Falcon
   */
  serviceName?: string;
}

/**
 * Falcon resource details
 */
export interface FalconResource extends Resource {
  properties: FalconResourceProperties;
}

/**
 * Tags object for patch operations.
 */
export interface TagsObject {
  /**
   * Resource tags.
   */
  tags?: { [propertyName: string]: string };
}

/**
 * The object that represents the operation.
 */
export interface OperationDisplay {
  /**
   * Service provider: Microsoft.Falcon
   */
  provider?: string;
  /**
   * Falcon Resource on which the operation is performed
   */
  resource?: string;
  /**
   * Operation type: Read, write, delete, etc.
   */
  operation?: string;
  /**
   * Description of the operation.
   */
  description?: string;
}

/**
 * The Falcon API operation
 */
export interface Operation {
  /**
   * Operation name: {Microsoft.Falcon}/{resource}/{operation}
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly name?: string;
  display?: OperationDisplay;
}

/**
 * An interface representing ErrorResponseError.
 */
export interface ErrorResponseError {
  /**
   * The error code.
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly code?: string;
  /**
   * The error message.
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly message?: string;
}

/**
 * The error response that indicates why an operation has failed.
 */
export interface ErrorResponse {
  error?: ErrorResponseError;
}

/**
 * Optional Parameters.
 */
export interface FalconResourcesUpdateTagsOptionalParams extends msRest.RequestOptionsBase {
  /**
   * Resource tags.
   */
  tags?: { [propertyName: string]: string };
}

/**
 * An interface representing FalconClientOptions.
 */
export interface FalconClientOptions extends AzureServiceClientOptions {
  baseUri?: string;
}

/**
 * @interface
 * The paginated list of Falcon resources
 * @extends Array<FalconResource>
 */
export interface FalconResourceListResult extends Array<FalconResource> {
  /**
   * The link to fetch the next page of Falcon resources
   */
  nextLink?: string;
}

/**
 * @interface
 * The paginated list of Falcon API operations.
 * @extends Array<Operation>
 */
export interface OperationListResult extends Array<Operation> {
  /**
   * The link to fetch the next page of Falcon API operations.
   */
  nextLink?: string;
}

/**
 * Contains response data for the get operation.
 */
export type ResourcesGetResponse = FalconResource & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: FalconResource;
    };
};

/**
 * Contains response data for the createAndUpdate operation.
 */
export type FalconResourcesCreateAndUpdateResponse = FalconResource & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: FalconResource;
    };
};

/**
 * Contains response data for the updateTags operation.
 */
export type FalconResourcesUpdateTagsResponse = FalconResource & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: FalconResource;
    };
};

/**
 * Contains response data for the listByResourceGroup operation.
 */
export type FalconResourcesListByResourceGroupResponse = FalconResourceListResult & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: FalconResourceListResult;
    };
};

/**
 * Contains response data for the listBySubscription operation.
 */
export type FalconResourcesListBySubscriptionResponse = FalconResourceListResult & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: FalconResourceListResult;
    };
};

/**
 * Contains response data for the listByResourceGroupNext operation.
 */
export type FalconResourcesListByResourceGroupNextResponse = FalconResourceListResult & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: FalconResourceListResult;
    };
};

/**
 * Contains response data for the listBySubscriptionNext operation.
 */
export type FalconResourcesListBySubscriptionNextResponse = FalconResourceListResult & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: FalconResourceListResult;
    };
};

/**
 * Contains response data for the list operation.
 */
export type OperationsListResponse = OperationListResult & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: OperationListResult;
    };
};

/**
 * Contains response data for the listNext operation.
 */
export type OperationsListNextResponse = OperationListResult & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: OperationListResult;
    };
};
