/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";
import * as Models from "./models";
import * as Mappers from "./models/mappers";
import * as operations from "./operations";
import { MonitorManagementClientContext } from "./monitorManagementClientContext";


class MonitorManagementClient extends MonitorManagementClientContext {
  // Operation groups
  actionGroups: operations.ActionGroups;
  activityLogAlerts: operations.ActivityLogAlerts;

  /**
   * Initializes a new instance of the MonitorManagementClient class.
   * @param credentials Credentials needed for the client to connect to Azure.
   * @param subscriptionId The Azure subscription Id.
   * @param [options] The parameter options
   */
  constructor(credentials: msRest.ServiceClientCredentials, subscriptionId: string, options?: Models.MonitorManagementClientOptions) {
    super(credentials, subscriptionId, options);
    this.actionGroups = new operations.ActionGroups(this);
    this.activityLogAlerts = new operations.ActivityLogAlerts(this);
  }
}

// Operation Specifications

export {
  MonitorManagementClient,
  MonitorManagementClientContext,
  Models as MonitorManagementModels,
  Mappers as MonitorManagementMappers
};
export * from "./operations";
