/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import { ServiceClientOptions } from "@azure/ms-rest-js";
import * as msRest from "@azure/ms-rest-js";

/**
 * An interface representing DocumentFilter.
 */
export interface DocumentFilter {
  /**
   * A case-sensitive prefix string to filter documents in the source path for translation.
   * For example, when using a Azure storage blob Uri, use the prefix to restrict sub folders for
   * translation.
   */
  prefix?: string;
  /**
   * A case-sensitive suffix string to filter documents in the source path for translation.
   * This is most often use for file extensions
   */
  suffix?: string;
}

/**
 * Source of the input documents
 */
export interface SourceInput {
  /**
   * Location of the folder / container with your documents
   */
  sourceUrl: string;
  filter?: DocumentFilter;
  /**
   * Language code
   * If none is specified, we will perform auto detect on the document
   */
  language?: string;
  /**
   * Possible values include: 'AzureBlob'
   */
  storageSource?: StorageSource;
}

/**
 * Glossary / translation memory for the request
 */
export interface Glossary {
  /**
   * Location of the glossary.
   * We will use the file extension to extract the formating if the format parameter is not
   * supplied.
   *
   * If the translation language pair is not present in the glossary, it will not be applied
   */
  glossaryUrl: string;
  /**
   * Format
   */
  format?: string;
  /**
   * Version
   */
  version?: string;
}

/**
 * Destination for the finished translated documents
 */
export interface TargetInput {
  /**
   * Location of the folder / container with your documents
   */
  targetUrl: string;
  /**
   * Category / custom system for translation request
   */
  category?: string;
  /**
   * Target Language
   */
  language: string;
  /**
   * List of Glossary
   */
  glossaries?: Glossary[];
  /**
   * Possible values include: 'AzureBlob'
   */
  storageSource?: StorageSource1;
}

/**
 * Definition for the input batch translation request
 */
export interface BatchRequest {
  source: SourceInput;
  /**
   * Location of the destination for the output
   */
  targets: TargetInput[];
}

/**
 * Job submission batch request
 */
export interface JobSubmissionBatchRequest {
  /**
   * The input list of documents or folders containing documents
   */
  inputs: BatchRequest[];
}

/**
 * An interface representing DocumentStatusDetail.
 */
export interface DocumentStatusDetail {
  /**
   * Location of the document or folder
   */
  path: string;
  /**
   * Operation created date time
   */
  createdDateTimeUtc: Date;
  /**
   * Date time in which the operation's status has been updated
   */
  lastActionDateTimeUtc: Date;
  /**
   * Possible values include: 'NotStarted', 'Running', 'Succeeded', 'Failed', 'Cancelled',
   * 'Cancelling'
   */
  status: Status;
  /**
   * Detected language of the original document (to be implemented)
   */
  detectedLanguage?: string;
  /**
   * To language
   */
  to: string;
  /**
   * Error message if any
   */
  errorMessage?: string;
  /**
   * Error code if any
   */
  errorCode?: number;
  /**
   * Progress of the translation if available
   */
  progress?: number;
  /**
   * Document Id
   */
  id?: number;
}

/**
 * Document Status Response
 */
export interface DocumentStatusResponse {
  /**
   * The detail status of individual documents
   */
  value?: DocumentStatusDetail[];
  /**
   * Url for the next page.  Null if no more pages available
   */
  nextLink?: string;
}

/**
 * An interface representing StatusSummary.
 */
export interface StatusSummary {
  /**
   * Total count
   */
  total?: number;
  /**
   * Failed count
   */
  failed?: number;
  /**
   * Number of Success
   */
  success?: number;
  /**
   * Number of in progress
   */
  inProgress?: number;
  /**
   * Count of not yet started
   */
  notYetStarted?: number;
}

/**
 * Job status response
 */
export interface OperationStatusSummary {
  /**
   * Id of the operation.
   */
  id: string;
  /**
   * Operation created date time
   */
  createdDateTimeUtc: Date;
  /**
   * Date time in which the operation's status has been updated
   */
  lastActionDateTimeUtc: Date;
  /**
   * Possible values include: 'NotStarted', 'Running', 'Succeeded', 'Failed', 'Cancelled',
   * 'Cancelling'
   */
  status?: Status1;
  summary: StatusSummary;
}

/**
 * The response for a document submission
 */
export interface DocumentSubmissionResponse {
  job?: OperationStatusSummary;
  /**
   * Document download link
   */
  documentDownloadUrl?: string;
  /**
   * Datetime in Utc when the document will no longer be available
   */
  documentExpirationDateTimeUtc?: Date;
}

/**
 * Document Status Response
 */
export interface OperationStatusResponse {
  /**
   * The summary status of individual opearation
   */
  value?: OperationStatusSummary[];
  /**
   * Url for the next page.  Null if no more pages available
   */
  nextLink?: string;
}

/**
 * An interface representing FileFormat.
 */
export interface FileFormat {
  /**
   * Name of the format
   */
  format?: string;
  /**
   * Supported file extension for this format
   */
  fileExtensions?: string[];
  /**
   * Supported Content-Types for this format
   */
  contentTypes?: string[];
  /**
   * Supported Version
   */
  versions?: string[];
}

/**
 * Base type for List return in our api
 */
export interface FileFormatListResult {
  /**
   * list of objects
   */
  value?: FileFormat[];
}

/**
 * Base type for List return in our api
 */
export interface StorageSourceListResult {
  /**
   * list of objects
   */
  value?: string[];
}

/**
 * New Inner Error format which conforms to Cognitive Services API Guidelines which is available at
 * https://microsoft.sharepoint.com/%3Aw%3A/t/CognitiveServicesPMO/EUoytcrjuJdKpeOKIK_QRC8BPtUYQpKBi8JsWyeDMRsWlQ?e=CPq8ow.
 * This contains required properties ErrorCode, message and optional properties target, details(key
 * value pair), inner error(this can be nested).
 */
export interface InnerErrorV2 {
  /**
   * Gets detailed error code.
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly code?: number;
  /**
   * Gets detailed error string.
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly error?: string;
  /**
   * Gets high level error message.
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly message?: string;
  /**
   * Gets the source of the error.
   * For example it would be "documents" or "document id" in case of invalid document.
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly target?: string;
  innerError?: InnerErrorV2;
}

/**
 * This contains an outer error with error code, message, details, target and an inner error with
 * more descriptive details.
 */
export interface ErrorV2 {
  /**
   * Possible values include: 'InvalidRequest', 'InvalidArgument', 'InternalServerError',
   * 'ServiceUnavailable', 'ResourceNotFound', 'Unauthorized', 'RequestRateTooHigh'
   */
  code?: Code;
  /**
   * Gets high level error message.
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly message?: string;
  /**
   * Gets the source of the error.
   * For example it would be "documents" or "document id" in case of invalid document.
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly target?: string;
  innerError?: InnerErrorV2;
}

/**
 * Contains unified error information used for HTTP responses across any Cognitive Service.
 * Instances
 * can be created either through Microsoft.CloudAI.Containers.HttpStatusExceptionV2 or by returning
 * it directly from
 * a controller.
 */
export interface ErrorResponseV2 {
  error?: ErrorV2;
}

/**
 * An interface representing BatchTextTranslationAPIOptions.
 */
export interface BatchTextTranslationAPIOptions extends ServiceClientOptions {
  baseUri?: string;
}

/**
 * Optional Parameters.
 */
export interface BatchTextTranslationAPIBatchDocumentsSubmitOptionalParams extends msRest.RequestOptionsBase {
  /**
   * request details
   */
  body?: JobSubmissionBatchRequest;
}

/**
 * Optional Parameters.
 */
export interface BatchTextTranslationAPIGetDetailedDocumentStatusOptionalParams extends msRest.RequestOptionsBase {
  /**
   * Take the $top entries in the collection
   * When both $top and $skip are supplied, $skip is applied first. Default value: 50.
   */
  top?: number;
  /**
   * Skip the $skip entries in the collection
   * When both $top and $skip are supplied, $skip is applied first. Default value: 0.
   */
  skip?: number;
}

/**
 * Optional Parameters.
 */
export interface BatchTextTranslationAPISingleDocumentUploadOptionalParams extends msRest.RequestOptionsBase {
  /**
   * The language code of the original document
   * If none is specified, we will perform auto detect on the document
   */
  sourceLanguage?: string;
  /**
   * Category for the translation system (Optional)
   */
  category?: string;
}

/**
 * Optional Parameters.
 */
export interface BatchTextTranslationAPIGetDetailedDocumentStatusForAGivenOperationIdOptionalParams extends msRest.RequestOptionsBase {
  /**
   * Take the $top entries in the collection
   * When both $top and $skip are supplied, $skip is applied first. Default value: 50.
   */
  top?: number;
  /**
   * Skip the $skip entries in the collection
   * When both $top and $skip are supplied, $skip is applied first. Default value: 0.
   */
  skip?: number;
}

/**
 * Optional Parameters.
 */
export interface BatchTextTranslationAPIGetStatusOfOperationListOptionalParams extends msRest.RequestOptionsBase {
  /**
   * Take the $top entries in the collection
   * When both $top and $skip are supplied, $skip is applied first. Default value: 50.
   */
  top?: number;
  /**
   * Skip the $skip entries in the collection
   * When both $top and $skip are supplied, $skip is applied first. Default value: 0.
   */
  skip?: number;
}

/**
 * Defines headers for Batch Documents Submit operation.
 */
export interface BatchDocumentsSubmitHeaders {
  /**
   * Location of the operation
   */
  operationLocation: string;
}

/**
 * Defines headers for Get Detailed Document Status operation.
 */
export interface GetDetailedDocumentStatusHeaders {
  /**
   * Indicates how long to wait before making a new request.
   */
  retryAfter: number;
  /**
   * The ETag response-header field provides the current value of the entity tag for the requested
   * variant. Used with If-Match, If-None-Match and If-Range to implement optimistic concurrency
   * control.
   */
  eTag: string;
}

/**
 * Defines headers for Single Document Upload operation.
 */
export interface SingleDocumentUploadHeaders {
  /**
   * Location of the document status
   */
  location: string;
  /**
   * Location of the operation
   */
  operationLocation: string;
}

/**
 * Defines headers for Get Document Status operation.
 */
export interface GetDocumentStatusHeaders {
  /**
   * Indicates how long to wait before making a new request.
   */
  retryAfter: number;
  /**
   * The ETag response-header field provides the current value of the entity tag for the requested
   * variant. Used with If-Match, If-None-Match and If-Range to implement optimistic concurrency
   * control.
   */
  eTag: string;
}

/**
 * Defines headers for Get Operation Status operation.
 */
export interface GetOperationStatusHeaders {
  /**
   * Indicates how long to wait before making a new request.
   */
  retryAfter: number;
  /**
   * The ETag response-header field provides the current value of the entity tag for the requested
   * variant. Used with If-Match, If-None-Match and If-Range to implement optimistic concurrency
   * control.
   */
  eTag: string;
}

/**
 * Defines headers for Get Detailed Document Status for a given operation id operation.
 */
export interface GetDetailedDocumentStatusforagivenoperationidHeaders {
  /**
   * Indicates how long to wait before making a new request.
   */
  retryAfter: number;
  /**
   * The ETag response-header field provides the current value of the entity tag for the requested
   * variant. Used with If-Match, If-None-Match and If-Range to implement optimistic concurrency
   * control.
   */
  eTag: string;
}

/**
 * Defines headers for Get status of operation list operation.
 */
export interface GetstatusofoperationlistHeaders {
  /**
   * Indicates how long to wait before making a new request.
   */
  retryAfter: number;
  /**
   * The ETag response-header field provides the current value of the entity tag for the requested
   * variant. Used with If-Match, If-None-Match and If-Range to implement optimistic concurrency
   * control.
   */
  eTag: string;
}

/**
 * Defines values for StorageSource.
 * Possible values include: 'AzureBlob'
 * @readonly
 * @enum {string}
 */
export type StorageSource = 'AzureBlob';

/**
 * Defines values for StorageSource1.
 * Possible values include: 'AzureBlob'
 * @readonly
 * @enum {string}
 */
export type StorageSource1 = 'AzureBlob';

/**
 * Defines values for Status.
 * Possible values include: 'NotStarted', 'Running', 'Succeeded', 'Failed', 'Cancelled',
 * 'Cancelling'
 * @readonly
 * @enum {string}
 */
export type Status = 'NotStarted' | 'Running' | 'Succeeded' | 'Failed' | 'Cancelled' | 'Cancelling';

/**
 * Defines values for Status1.
 * Possible values include: 'NotStarted', 'Running', 'Succeeded', 'Failed', 'Cancelled',
 * 'Cancelling'
 * @readonly
 * @enum {string}
 */
export type Status1 = 'NotStarted' | 'Running' | 'Succeeded' | 'Failed' | 'Cancelled' | 'Cancelling';

/**
 * Defines values for Code.
 * Possible values include: 'InvalidRequest', 'InvalidArgument', 'InternalServerError',
 * 'ServiceUnavailable', 'ResourceNotFound', 'Unauthorized', 'RequestRateTooHigh'
 * @readonly
 * @enum {string}
 */
export type Code = 'InvalidRequest' | 'InvalidArgument' | 'InternalServerError' | 'ServiceUnavailable' | 'ResourceNotFound' | 'Unauthorized' | 'RequestRateTooHigh';

/**
 * Contains response data for the batchDocumentsSubmit operation.
 */
export type BatchDocumentsSubmitResponse = ErrorResponseV2 & BatchDocumentsSubmitHeaders & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The parsed HTTP response headers.
       */
      parsedHeaders: BatchDocumentsSubmitHeaders;

      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: ErrorResponseV2;
    };
};

/**
 * Contains response data for the getDetailedDocumentStatus operation.
 */
export type GetDetailedDocumentStatusResponse = GetDetailedDocumentStatusHeaders & {
  /**
   * The parsed response body.
   */
  body: any;

  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The parsed HTTP response headers.
       */
      parsedHeaders: GetDetailedDocumentStatusHeaders;

      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the singleDocumentUpload operation.
 */
export type SingleDocumentUploadResponse = SingleDocumentUploadHeaders & {
  /**
   * The parsed response body.
   */
  body: any;

  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The parsed HTTP response headers.
       */
      parsedHeaders: SingleDocumentUploadHeaders;

      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the getDocumentStatus operation.
 */
export type GetDocumentStatusResponse = GetDocumentStatusHeaders & {
  /**
   * The parsed response body.
   */
  body: any;

  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The parsed HTTP response headers.
       */
      parsedHeaders: GetDocumentStatusHeaders;

      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the getOperationStatus operation.
 */
export type GetOperationStatusResponse = GetOperationStatusHeaders & {
  /**
   * The parsed response body.
   */
  body: any;

  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The parsed HTTP response headers.
       */
      parsedHeaders: GetOperationStatusHeaders;

      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the cancelOperation operation.
 */
export type CancelOperationResponse = {
  /**
   * The parsed response body.
   */
  body: any;

  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the getDetailedDocumentStatusForAGivenOperationId operation.
 */
export type GetDetailedDocumentStatusforagivenoperationidResponse = GetDetailedDocumentStatusforagivenoperationidHeaders & {
  /**
   * The parsed response body.
   */
  body: any;

  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The parsed HTTP response headers.
       */
      parsedHeaders: GetDetailedDocumentStatusforagivenoperationidHeaders;

      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the getStatusOfOperationList operation.
 */
export type GetstatusofoperationlistResponse = GetstatusofoperationlistHeaders & {
  /**
   * The parsed response body.
   */
  body: any;

  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The parsed HTTP response headers.
       */
      parsedHeaders: GetstatusofoperationlistHeaders;

      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the getDocumentFormats operation.
 */
export type GetDocumentFormatsResponse = {
  /**
   * The parsed response body.
   */
  body: any;

  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the getGlossaryFormats operation.
 */
export type GetGlossaryFormatsResponse = {
  /**
   * The parsed response body.
   */
  body: any;

  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};

/**
 * Contains response data for the getStorageSourcesThatWeCurrentlySupport operation.
 */
export type GetStorageSourcesThatWeCurrentlySupportResponse = {
  /**
   * The parsed response body.
   */
  body: any;

  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: any;
    };
};
